{-# OPTIONS -w -O0 #-}
{- |
Module      :  CASL_DL/ATC_CASL_DL.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'CASL_DL.AS_CASL_DL.CardType'
'CASL_DL.AS_CASL_DL.DL_FORMULA'
'CASL_DL.Sign.CASL_DLSign'
'CASL_DL.Sign.PropertyType'
'CASL_DL.Sign.AnnoAppl'
'CASL_DL.Sign.AnnoLiteral'
'CASL_DL.Sublogics.CASL_DL_SL'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
CASL_DL/AS_CASL_DL.hs
CASL_DL/Sign.hs
CASL_DL/Sublogics.hs
-}

module CASL_DL.ATC_CASL_DL () where

import ATerm.Lib
import CASL.AS_Basic_CASL
import CASL.ATC_CASL
import CASL_DL.AS_CASL_DL
import CASL_DL.Print_AS ()
import CASL_DL.Sign
import CASL_DL.Sublogics
import Common.AS_Annotation
import Common.Doc
import Common.DocUtils
import Common.Id
import Control.Exception
import Data.List (union, (\\), isPrefixOf)
import Data.Typeable
import qualified Data.Map as Map

{-! for CASL_DL.AS_CASL_DL.CardType derive : Typeable !-}
{-! for CASL_DL.AS_CASL_DL.DL_FORMULA derive : Typeable !-}
{-! for CASL_DL.Sign.CASL_DLSign derive : Typeable !-}
{-! for CASL_DL.Sign.PropertyType derive : Typeable !-}
{-! for CASL_DL.Sign.AnnoAppl derive : Typeable !-}
{-! for CASL_DL.Sign.AnnoLiteral derive : Typeable !-}
{-! for CASL_DL.Sublogics.CASL_DL_SL derive : Typeable !-}

{-! for CASL_DL.AS_CASL_DL.CardType derive : ShATermConvertible !-}
{-! for CASL_DL.AS_CASL_DL.DL_FORMULA derive : ShATermConvertible !-}
{-! for CASL_DL.Sign.CASL_DLSign derive : ShATermConvertible !-}
{-! for CASL_DL.Sign.PropertyType derive : ShATermConvertible !-}
{-! for CASL_DL.Sign.AnnoAppl derive : ShATermConvertible !-}
{-! for CASL_DL.Sign.AnnoLiteral derive : ShATermConvertible !-}
{-! for CASL_DL.Sublogics.CASL_DL_SL derive : ShATermConvertible !-}
