{-# OPTIONS -w -O0 #-}
{- |
Module      :  ConstraintCASL/ATC_ConstraintCASL.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'ConstraintCASL.AS_ConstraintCASL.ConstraintFORMULA'
'ConstraintCASL.AS_ConstraintCASL.RELATION'
'ConstraintCASL.AS_ConstraintCASL.ATOMCONJUNCTION'
'ConstraintCASL.AS_ConstraintCASL.ATOM'
'ConstraintCASL.AS_ConstraintCASL.ConstraintTERM'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
ConstraintCASL/AS_ConstraintCASL.hs
-}

module ConstraintCASL.ATC_ConstraintCASL () where

import ATerm.Lib
import CASL.AS_Basic_CASL
import CASL.ATC_CASL
import Common.Id
import ConstraintCASL.AS_ConstraintCASL
import Data.Typeable

{-! for ConstraintCASL.AS_ConstraintCASL.ConstraintFORMULA derive : Typeable !-}
{-! for ConstraintCASL.AS_ConstraintCASL.RELATION derive : Typeable !-}
{-! for ConstraintCASL.AS_ConstraintCASL.ATOMCONJUNCTION derive : Typeable !-}
{-! for ConstraintCASL.AS_ConstraintCASL.ATOM derive : Typeable !-}
{-! for ConstraintCASL.AS_ConstraintCASL.ConstraintTERM derive : Typeable !-}

{-! for ConstraintCASL.AS_ConstraintCASL.ConstraintFORMULA derive : ShATermConvertible !-}
{-! for ConstraintCASL.AS_ConstraintCASL.RELATION derive : ShATermConvertible !-}
{-! for ConstraintCASL.AS_ConstraintCASL.ATOMCONJUNCTION derive : ShATermConvertible !-}
{-! for ConstraintCASL.AS_ConstraintCASL.ATOM derive : ShATermConvertible !-}
{-! for ConstraintCASL.AS_ConstraintCASL.ConstraintTERM derive : ShATermConvertible !-}
