{-# OPTIONS -w -O0 #-}
{- |
Module      :  Isabelle/ATC_Isabelle.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'Isabelle.IsaSign.VName'
'Isabelle.IsaSign.AltSyntax'
'Isabelle.IsaSign.Indexname'
'Isabelle.IsaSign.IsaClass'
'Isabelle.IsaSign.Typ'
'Isabelle.IsaSign.Continuity'
'Isabelle.IsaSign.TAttr'
'Isabelle.IsaSign.DTyp'
'Isabelle.IsaSign.Term'
'Isabelle.IsaSign.Sentence'
'Isabelle.IsaSign.SetDecl'
'Isabelle.IsaSign.MetaTerm'
'Isabelle.IsaSign.TypeSig'
'Isabelle.IsaSign.BaseSig'
'Isabelle.IsaSign.Sign'
'Isabelle.IsaSign.IsaProof'
'Isabelle.IsaSign.ProofCommand'
'Isabelle.IsaSign.ProofEnd'
'Isabelle.IsaSign.Modifier'
'Isabelle.IsaSign.ProofMethod'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
Isabelle/IsaSign.hs
-}

module Isabelle.ATC_Isabelle () where

import ATerm.Lib
import Data.List
import Data.Typeable
import Isabelle.IsaSign
import qualified Data.Map as Map

{-! for Isabelle.IsaSign.VName derive : Typeable !-}
{-! for Isabelle.IsaSign.AltSyntax derive : Typeable !-}
{-! for Isabelle.IsaSign.Indexname derive : Typeable !-}
{-! for Isabelle.IsaSign.IsaClass derive : Typeable !-}
{-! for Isabelle.IsaSign.Typ derive : Typeable !-}
{-! for Isabelle.IsaSign.Continuity derive : Typeable !-}
{-! for Isabelle.IsaSign.TAttr derive : Typeable !-}
{-! for Isabelle.IsaSign.DTyp derive : Typeable !-}
{-! for Isabelle.IsaSign.Term derive : Typeable !-}
{-! for Isabelle.IsaSign.Sentence derive : Typeable !-}
{-! for Isabelle.IsaSign.SetDecl derive : Typeable !-}
{-! for Isabelle.IsaSign.MetaTerm derive : Typeable !-}
{-! for Isabelle.IsaSign.TypeSig derive : Typeable !-}
{-! for Isabelle.IsaSign.BaseSig derive : Typeable !-}
{-! for Isabelle.IsaSign.Sign derive : Typeable !-}
{-! for Isabelle.IsaSign.IsaProof derive : Typeable !-}
{-! for Isabelle.IsaSign.ProofCommand derive : Typeable !-}
{-! for Isabelle.IsaSign.ProofEnd derive : Typeable !-}
{-! for Isabelle.IsaSign.Modifier derive : Typeable !-}
{-! for Isabelle.IsaSign.ProofMethod derive : Typeable !-}

{-! for Isabelle.IsaSign.VName derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.AltSyntax derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.Indexname derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.IsaClass derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.Typ derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.Continuity derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.TAttr derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.DTyp derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.Term derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.Sentence derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.SetDecl derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.MetaTerm derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.TypeSig derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.BaseSig derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.Sign derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.IsaProof derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.ProofCommand derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.ProofEnd derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.Modifier derive : ShATermConvertible !-}
{-! for Isabelle.IsaSign.ProofMethod derive : ShATermConvertible !-}
