{-# OPTIONS -w -O0 #-}
{- |
Module      :  RDF/ATC_RDF.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'RDF.AS.TurtleDocument'
'RDF.AS.Statement'
'RDF.AS.Prefix'
'RDF.AS.Base'
'RDF.AS.Triples'
'RDF.AS.Subject'
'RDF.AS.Predicate'
'RDF.AS.Object'
'RDF.AS.PredicateObjectList'
'RDF.AS.RDFLiteral'
'RDF.AS.Term'
'RDF.AS.Axiom'
'RDF.AS.RDFEntityType'
'RDF.AS.RDFEntity'
'OWL2.AS.IRIType'
'OWL2.AS.QName'
'OWL2.AS.EquivOrDisjoint'
'OWL2.AS.DomainOrRange'
'OWL2.AS.SameOrDifferent'
'OWL2.AS.Relation'
'OWL2.AS.Character'
'OWL2.AS.PositiveOrNegative'
'OWL2.AS.QuantifierType'
'OWL2.AS.DatatypeCat'
'OWL2.AS.CardinalityType'
'OWL2.AS.Cardinality'
'OWL2.AS.JunctionType'
'OWL2.AS.Entity'
'OWL2.AS.EntityType'
'OWL2.AS.TypedOrUntyped'
'OWL2.AS.Literal'
'OWL2.AS.NNInt'
'OWL2.AS.IntLit'
'OWL2.AS.DecLit'
'OWL2.AS.FloatLit'
'OWL2.AS.ObjectPropertyExpression'
'OWL2.AS.DataRange'
'OWL2.AS.ClassExpression'
'OWL2.AS.Annotation'
'OWL2.AS.AnnotationValue'
'RDF.Symbols.SymbItems'
'RDF.Symbols.SymbMapItems'
'RDF.Symbols.RawSymb'
'RDF.Sign.Sign'
'RDF.Morphism.RDFMorphism'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
RDF/AS.hs
OWL2/AS.hs
RDF/Symbols.hs
RDF/Sign.hs
RDF/Morphism.hs
RDF/Sublogic.hs
-}

module RDF.ATC_RDF () where

import ATC.Result
import ATerm.Lib
import Common.DocUtils
import Common.Id
import Common.Result
import Data.Char (intToDigit)
import Data.List
import Data.Maybe
import Data.Typeable
import OWL2.AS
import OWL2.ColonKeywords
import OWL2.Keywords
import RDF.AS
import RDF.Function
import RDF.Morphism
import RDF.Print ()
import RDF.Sign
import RDF.Sublogic
import RDF.Symbols
import qualified Data.Map as Map
import qualified Data.Set as Set

{-! for RDF.AS.TurtleDocument derive : Typeable !-}
{-! for RDF.AS.Statement derive : Typeable !-}
{-! for RDF.AS.Prefix derive : Typeable !-}
{-! for RDF.AS.Base derive : Typeable !-}
{-! for RDF.AS.Triples derive : Typeable !-}
{-! for RDF.AS.Subject derive : Typeable !-}
{-! for RDF.AS.Predicate derive : Typeable !-}
{-! for RDF.AS.Object derive : Typeable !-}
{-! for RDF.AS.PredicateObjectList derive : Typeable !-}
{-! for RDF.AS.RDFLiteral derive : Typeable !-}
{-! for RDF.AS.Term derive : Typeable !-}
{-! for RDF.AS.Axiom derive : Typeable !-}
{-! for RDF.AS.RDFEntityType derive : Typeable !-}
{-! for RDF.AS.RDFEntity derive : Typeable !-}
{-! for OWL2.AS.IRIType derive : Typeable !-}
{-! for OWL2.AS.QName derive : Typeable !-}
{-! for OWL2.AS.EquivOrDisjoint derive : Typeable !-}
{-! for OWL2.AS.DomainOrRange derive : Typeable !-}
{-! for OWL2.AS.SameOrDifferent derive : Typeable !-}
{-! for OWL2.AS.Relation derive : Typeable !-}
{-! for OWL2.AS.Character derive : Typeable !-}
{-! for OWL2.AS.PositiveOrNegative derive : Typeable !-}
{-! for OWL2.AS.QuantifierType derive : Typeable !-}
{-! for OWL2.AS.DatatypeCat derive : Typeable !-}
{-! for OWL2.AS.CardinalityType derive : Typeable !-}
{-! for OWL2.AS.Cardinality derive : Typeable !-}
{-! for OWL2.AS.JunctionType derive : Typeable !-}
{-! for OWL2.AS.Entity derive : Typeable !-}
{-! for OWL2.AS.EntityType derive : Typeable !-}
{-! for OWL2.AS.TypedOrUntyped derive : Typeable !-}
{-! for OWL2.AS.Literal derive : Typeable !-}
{-! for OWL2.AS.NNInt derive : Typeable !-}
{-! for OWL2.AS.IntLit derive : Typeable !-}
{-! for OWL2.AS.DecLit derive : Typeable !-}
{-! for OWL2.AS.FloatLit derive : Typeable !-}
{-! for OWL2.AS.ObjectPropertyExpression derive : Typeable !-}
{-! for OWL2.AS.DataRange derive : Typeable !-}
{-! for OWL2.AS.ClassExpression derive : Typeable !-}
{-! for OWL2.AS.Annotation derive : Typeable !-}
{-! for OWL2.AS.AnnotationValue derive : Typeable !-}
{-! for RDF.Symbols.SymbItems derive : Typeable !-}
{-! for RDF.Symbols.SymbMapItems derive : Typeable !-}
{-! for RDF.Symbols.RawSymb derive : Typeable !-}
{-! for RDF.Sign.Sign derive : Typeable !-}
{-! for RDF.Morphism.RDFMorphism derive : Typeable !-}

{-! for RDF.AS.TurtleDocument derive : ShATermConvertible !-}
{-! for RDF.AS.Statement derive : ShATermConvertible !-}
{-! for RDF.AS.Prefix derive : ShATermConvertible !-}
{-! for RDF.AS.Base derive : ShATermConvertible !-}
{-! for RDF.AS.Triples derive : ShATermConvertible !-}
{-! for RDF.AS.Subject derive : ShATermConvertible !-}
{-! for RDF.AS.Predicate derive : ShATermConvertible !-}
{-! for RDF.AS.Object derive : ShATermConvertible !-}
{-! for RDF.AS.PredicateObjectList derive : ShATermConvertible !-}
{-! for RDF.AS.RDFLiteral derive : ShATermConvertible !-}
{-! for RDF.AS.Term derive : ShATermConvertible !-}
{-! for RDF.AS.Axiom derive : ShATermConvertible !-}
{-! for RDF.AS.RDFEntityType derive : ShATermConvertible !-}
{-! for RDF.AS.RDFEntity derive : ShATermConvertible !-}
{-! for OWL2.AS.IRIType derive : ShATermConvertible !-}
{-! for OWL2.AS.QName derive : ShATermConvertible !-}
{-! for OWL2.AS.EquivOrDisjoint derive : ShATermConvertible !-}
{-! for OWL2.AS.DomainOrRange derive : ShATermConvertible !-}
{-! for OWL2.AS.SameOrDifferent derive : ShATermConvertible !-}
{-! for OWL2.AS.Relation derive : ShATermConvertible !-}
{-! for OWL2.AS.Character derive : ShATermConvertible !-}
{-! for OWL2.AS.PositiveOrNegative derive : ShATermConvertible !-}
{-! for OWL2.AS.QuantifierType derive : ShATermConvertible !-}
{-! for OWL2.AS.DatatypeCat derive : ShATermConvertible !-}
{-! for OWL2.AS.CardinalityType derive : ShATermConvertible !-}
{-! for OWL2.AS.Cardinality derive : ShATermConvertible !-}
{-! for OWL2.AS.JunctionType derive : ShATermConvertible !-}
{-! for OWL2.AS.Entity derive : ShATermConvertible !-}
{-! for OWL2.AS.EntityType derive : ShATermConvertible !-}
{-! for OWL2.AS.TypedOrUntyped derive : ShATermConvertible !-}
{-! for OWL2.AS.Literal derive : ShATermConvertible !-}
{-! for OWL2.AS.NNInt derive : ShATermConvertible !-}
{-! for OWL2.AS.IntLit derive : ShATermConvertible !-}
{-! for OWL2.AS.DecLit derive : ShATermConvertible !-}
{-! for OWL2.AS.FloatLit derive : ShATermConvertible !-}
{-! for OWL2.AS.ObjectPropertyExpression derive : ShATermConvertible !-}
{-! for OWL2.AS.DataRange derive : ShATermConvertible !-}
{-! for OWL2.AS.ClassExpression derive : ShATermConvertible !-}
{-! for OWL2.AS.Annotation derive : ShATermConvertible !-}
{-! for OWL2.AS.AnnotationValue derive : ShATermConvertible !-}
{-! for RDF.Symbols.SymbItems derive : ShATermConvertible !-}
{-! for RDF.Symbols.SymbMapItems derive : ShATermConvertible !-}
{-! for RDF.Symbols.RawSymb derive : ShATermConvertible !-}
{-! for RDF.Sign.Sign derive : ShATermConvertible !-}
{-! for RDF.Morphism.RDFMorphism derive : ShATermConvertible !-}
