{-# LANGUAGE StandaloneDeriving, ExistentialQuantification, DeriveDataTypeable #-}
{- |
Module      :  $Header$
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  nevrenato@gmail.com
Stability   :  experimental
Portability :  portable

Description :
Abstract syntax for hybrid logic with an arbitrary logic
below. 
-}

module TopHybrid.AS_TopHybrid where

import Common.Id
import Data.Typeable
import ATerm.Lib
-- DrIFT command
{-! global: GetRange !-}


data TH_BSPEC s = Bspec TH_BASIC_ITEM 
                | ExtSpec s
                  deriving Show 

data TH_BASIC_ITEM = Simple_mod_decl [MODALITY] Range
                   | Simple_nom_decl [NOMINAL] Range 
                     deriving Show

type MODALITY = SIMPLE_ID
type NOMINAL = SIMPLE_ID

data TH_FORMULA f = At NOMINAL (TH_FORMULA f) Range 
                  | Box MODALITY (TH_FORMULA f) Range
                  | Dia MODALITY (TH_FORMULA f) Range
                  | UnderLogic f
                  | Here NOMINAL Range  
                    deriving (Show, Eq, Ord)

data Form_Wrapper = forall f. (Show f, GetRange f, ShATermConvertible f) 
                                => Form_Wrapper (TH_FORMULA f)
data Spec_Wrapper = forall s. (Show s, GetRange s, ShATermConvertible s) 
                                => Spec_Wrapper (TH_BSPEC s)

----- Boring instances needed for a valid program, that DriFT cannot generate
deriving instance Show Form_Wrapper
deriving instance Show Spec_Wrapper
deriving instance Typeable Form_Wrapper
deriving instance Typeable Spec_Wrapper

instance Eq Form_Wrapper where
       (==) = undefined 
instance Eq Spec_Wrapper where
       (==) = undefined
instance Ord Form_Wrapper where
       compare = undefined
instance Ord Spec_Wrapper where
        compare = undefined 

instance GetRange Form_Wrapper where
        getRange (Form_Wrapper f) = getRange f
        rangeSpan (Form_Wrapper f) = rangeSpan f

instance GetRange Spec_Wrapper where
        getRange (Spec_Wrapper s) = getRange s
        rangeSpan (Spec_Wrapper s) = rangeSpan s



-- Generated by DrIFT, look but don't touch!

instance GetRange s => GetRange (TH_BSPEC s) where
  getRange = const nullRange
  rangeSpan x = case x of
    Bspec a -> joinRanges [rangeSpan a]
    ExtSpec a -> joinRanges [rangeSpan a]

instance GetRange TH_BASIC_ITEM where
  getRange x = case x of
    Simple_mod_decl _ p -> p
    Simple_nom_decl _ p -> p
  rangeSpan x = case x of
    Simple_mod_decl a b -> joinRanges [rangeSpan a, rangeSpan b]
    Simple_nom_decl a b -> joinRanges [rangeSpan a, rangeSpan b]

instance GetRange f => GetRange (TH_FORMULA f) where
  getRange x = case x of
    At _ _ p -> p
    Box _ _ p -> p
    Dia _ _ p -> p
    UnderLogic _ -> nullRange
    Here _ p -> p
  rangeSpan x = case x of
    At a b c -> joinRanges [rangeSpan a, rangeSpan b, rangeSpan c]
    Box a b c -> joinRanges [rangeSpan a, rangeSpan b, rangeSpan c]
    Dia a b c -> joinRanges [rangeSpan a, rangeSpan b, rangeSpan c]
    UnderLogic a -> joinRanges [rangeSpan a]
    Here a b -> joinRanges [rangeSpan a, rangeSpan b]
