{- |
Module      :  $Header$
Copyright   :  (c) T.Mossakowski, W.Herding, C.Maeder, Uni Bremen 2004-2006
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  till@informatik.uni-bremen.de
Stability   :  provisional
Portability :  portable

Abstract syntax for modal logic extension of CASL
  Only the added syntax is specified
-}

module Modal.AS_Modal where

import Common.Id
import Common.AS_Annotation
import CASL.AS_Basic_CASL

-- DrIFT command
{-! global: GetRange !-}

type M_BASIC_SPEC = BASIC_SPEC M_BASIC_ITEM M_SIG_ITEM M_FORMULA

type AnModFORM = Annoted (FORMULA M_FORMULA)

data M_BASIC_ITEM = Simple_mod_decl [Annoted SIMPLE_ID] [AnModFORM] Range
                  | Term_mod_decl [Annoted SORT] [AnModFORM] Range
                    deriving Show

data RIGOR = Rigid | Flexible deriving Show

data M_SIG_ITEM =
          Rigid_op_items RIGOR [Annoted (OP_ITEM M_FORMULA)] Range
                 -- pos: op, semi colons
        | Rigid_pred_items RIGOR [Annoted (PRED_ITEM M_FORMULA)] Range
                 -- pos: pred, semi colons
             deriving Show

data MODALITY = Simple_mod SIMPLE_ID | Term_mod (TERM M_FORMULA)
             deriving (Eq, Ord, Show)

data M_FORMULA = BoxOrDiamond Bool MODALITY (FORMULA M_FORMULA) Range
               -- The identifier and the term specify the kind of the modality
               -- pos: "[]" or  "<>", True if Box, False if Diamond
             deriving (Eq, Ord, Show)


-- Generated by DrIFT, look but don't touch!

instance GetRange M_BASIC_ITEM where
  getRange x = case x of
    Simple_mod_decl _ _ p -> p
    Term_mod_decl _ _ p -> p
  rangeSpan x = case x of
    Simple_mod_decl a b c -> joinRanges [rangeSpan a, rangeSpan b,
                                         rangeSpan c]
    Term_mod_decl a b c -> joinRanges [rangeSpan a, rangeSpan b,
                                       rangeSpan c]

instance GetRange RIGOR where
  getRange = const nullRange
  rangeSpan x = case x of
    Rigid -> []
    Flexible -> []

instance GetRange M_SIG_ITEM where
  getRange x = case x of
    Rigid_op_items _ _ p -> p
    Rigid_pred_items _ _ p -> p
  rangeSpan x = case x of
    Rigid_op_items a b c -> joinRanges [rangeSpan a, rangeSpan b,
                                        rangeSpan c]
    Rigid_pred_items a b c -> joinRanges [rangeSpan a, rangeSpan b,
                                          rangeSpan c]

instance GetRange MODALITY where
  getRange = const nullRange
  rangeSpan x = case x of
    Simple_mod a -> joinRanges [rangeSpan a]
    Term_mod a -> joinRanges [rangeSpan a]

instance GetRange M_FORMULA where
  getRange x = case x of
    BoxOrDiamond _ _ _ p -> p
  rangeSpan x = case x of
    BoxOrDiamond a b c d -> joinRanges [rangeSpan a, rangeSpan b,
                                        rangeSpan c, rangeSpan d]
