{-# OPTIONS -w -O0 #-}
{- |
Module      :  CASL/ATC_CASL.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'CASL.Sublogic.CASL_Formulas'
'CASL.Sublogic.SubsortingFeatures'
'CASL.Sublogic.SortGenerationFeatures'
'CASL.Sublogic.CASL_SL'
'CASL.Morphism.RawSymbol'
'CASL.Morphism.Morphism'
'CASL.Morphism.DefMorExt'
'CASL.Sign.OpType'
'CASL.Sign.PredType'
'CASL.Sign.SymbType'
'CASL.Sign.Symbol'
'CASL.Sign.Sign'
'CASL.AS_Basic_CASL.BASIC_SPEC'
'CASL.AS_Basic_CASL.BASIC_ITEMS'
'CASL.AS_Basic_CASL.SortsKind'
'CASL.AS_Basic_CASL.SIG_ITEMS'
'CASL.AS_Basic_CASL.SORT_ITEM'
'CASL.AS_Basic_CASL.OP_ITEM'
'CASL.AS_Basic_CASL.OpKind'
'CASL.AS_Basic_CASL.OP_TYPE'
'CASL.AS_Basic_CASL.OP_HEAD'
'CASL.AS_Basic_CASL.OP_ATTR'
'CASL.AS_Basic_CASL.PRED_ITEM'
'CASL.AS_Basic_CASL.PRED_TYPE'
'CASL.AS_Basic_CASL.PRED_HEAD'
'CASL.AS_Basic_CASL.DATATYPE_DECL'
'CASL.AS_Basic_CASL.ALTERNATIVE'
'CASL.AS_Basic_CASL.COMPONENTS'
'CASL.AS_Basic_CASL.VAR_DECL'
'CASL.AS_Basic_CASL.FORMULA'
'CASL.AS_Basic_CASL.Constraint'
'CASL.AS_Basic_CASL.QUANTIFIER'
'CASL.AS_Basic_CASL.PRED_SYMB'
'CASL.AS_Basic_CASL.TERM'
'CASL.AS_Basic_CASL.OP_SYMB'
'CASL.AS_Basic_CASL.SYMB_ITEMS'
'CASL.AS_Basic_CASL.SYMB_MAP_ITEMS'
'CASL.AS_Basic_CASL.SYMB_KIND'
'CASL.AS_Basic_CASL.SYMB'
'CASL.AS_Basic_CASL.TYPE'
'CASL.AS_Basic_CASL.SYMB_OR_MAP'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
CASL/Sublogic.hs
CASL/Morphism.hs
CASL/Sign.hs
CASL/AS_Basic_CASL.der.hs
-}

module CASL.ATC_CASL () where

import ATC.GlobalAnnotations
import ATerm.Lib
import CASL.AS_Basic_CASL
import CASL.Fold
import CASL.Morphism
import CASL.Sign
import CASL.Sublogic
import CASL.ToDoc ()
import Common.AS_Annotation
import Common.Doc
import Common.DocUtils
import Common.GlobalAnnotations
import Common.Id
import Common.Keywords
import Common.Lattice
import Common.Prec (mkPrecIntMap, PrecMap)
import Common.Result
import Common.Utils (composeMap)
import Control.Monad
import Control.Monad (when, unless)
import Data.List (isPrefixOf)
import Data.Maybe
import Data.Maybe (fromMaybe)
import Data.Typeable
import qualified Common.Lib.MapSet as MapSet
import qualified Common.Lib.Rel as Rel
import qualified Common.Lib.State as State
import qualified Data.Map as Map
import qualified Data.Set as Set

{-! for CASL.Sublogic.CASL_Formulas derive : Typeable !-}
{-! for CASL.Sublogic.SubsortingFeatures derive : Typeable !-}
{-! for CASL.Sublogic.SortGenerationFeatures derive : Typeable !-}
{-! for CASL.Sublogic.CASL_SL derive : Typeable !-}
{-! for CASL.Morphism.RawSymbol derive : Typeable !-}
{-! for CASL.Morphism.Morphism derive : Typeable !-}
{-! for CASL.Morphism.DefMorExt derive : Typeable !-}
{-! for CASL.Sign.OpType derive : Typeable !-}
{-! for CASL.Sign.PredType derive : Typeable !-}
{-! for CASL.Sign.SymbType derive : Typeable !-}
{-! for CASL.Sign.Symbol derive : Typeable !-}
{-! for CASL.Sign.Sign derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.BASIC_SPEC derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.BASIC_ITEMS derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.SortsKind derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.SIG_ITEMS derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.SORT_ITEM derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.OP_ITEM derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.OpKind derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.OP_TYPE derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.OP_HEAD derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.OP_ATTR derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.PRED_ITEM derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.PRED_TYPE derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.PRED_HEAD derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.DATATYPE_DECL derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.ALTERNATIVE derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.COMPONENTS derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.VAR_DECL derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.FORMULA derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.Constraint derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.QUANTIFIER derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.PRED_SYMB derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.TERM derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.OP_SYMB derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.SYMB_ITEMS derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.SYMB_MAP_ITEMS derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.SYMB_KIND derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.SYMB derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.TYPE derive : Typeable !-}
{-! for CASL.AS_Basic_CASL.SYMB_OR_MAP derive : Typeable !-}

{-! for CASL.Sublogic.CASL_Formulas derive : ShATermConvertible !-}
{-! for CASL.Sublogic.SubsortingFeatures derive : ShATermConvertible !-}
{-! for CASL.Sublogic.SortGenerationFeatures derive : ShATermConvertible !-}
{-! for CASL.Sublogic.CASL_SL derive : ShATermConvertible !-}
{-! for CASL.Morphism.RawSymbol derive : ShATermConvertible !-}
{-! for CASL.Morphism.Morphism derive : ShATermConvertible !-}
{-! for CASL.Morphism.DefMorExt derive : ShATermConvertible !-}
{-! for CASL.Sign.OpType derive : ShATermConvertible !-}
{-! for CASL.Sign.PredType derive : ShATermConvertible !-}
{-! for CASL.Sign.SymbType derive : ShATermConvertible !-}
{-! for CASL.Sign.Symbol derive : ShATermConvertible !-}
{-! for CASL.Sign.Sign derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.BASIC_SPEC derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.BASIC_ITEMS derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.SortsKind derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.SIG_ITEMS derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.SORT_ITEM derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.OP_ITEM derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.OpKind derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.OP_TYPE derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.OP_HEAD derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.OP_ATTR derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.PRED_ITEM derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.PRED_TYPE derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.PRED_HEAD derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.DATATYPE_DECL derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.ALTERNATIVE derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.COMPONENTS derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.VAR_DECL derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.FORMULA derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.Constraint derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.QUANTIFIER derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.PRED_SYMB derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.TERM derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.OP_SYMB derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.SYMB_ITEMS derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.SYMB_MAP_ITEMS derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.SYMB_KIND derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.SYMB derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.TYPE derive : ShATermConvertible !-}
{-! for CASL.AS_Basic_CASL.SYMB_OR_MAP derive : ShATermConvertible !-}
