{-# OPTIONS -w -O0 #-}
{- |
Module      :  THF/ATC_THF.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'THF.As.TPTP_THF'
'THF.As.Comment'
'THF.As.DefinedComment'
'THF.As.SystemComment'
'THF.As.Include'
'THF.As.Annotations'
'THF.As.FormulaRole'
'THF.As.THFFormula'
'THF.As.THFLogicFormula'
'THF.As.THFBinaryFormula'
'THF.As.THFBinaryTuple'
'THF.As.THFUnitaryFormula'
'THF.As.THFQuantifiedFormula'
'THF.As.THFVariable'
'THF.As.THFTypedConst'
'THF.As.THFTypeFormula'
'THF.As.THFTypeableFormula'
'THF.As.THFSubType'
'THF.As.THFTopLevelType'
'THF.As.THFUnitaryType'
'THF.As.THFBinaryType'
'THF.As.THFAtom'
'THF.As.THFDefinedVar'
'THF.As.THFSequent'
'THF.As.THFConnTerm'
'THF.As.THFQuantifier'
'THF.As.Quantifier'
'THF.As.THFPairConnective'
'THF.As.THFUnaryConnective'
'THF.As.AssocConnective'
'THF.As.DefinedType'
'THF.As.DefinedPlainFormula'
'THF.As.DefinedProp'
'THF.As.DefinedPred'
'THF.As.Term'
'THF.As.FunctionTerm'
'THF.As.PlainTerm'
'THF.As.DefinedTerm'
'THF.As.DefinedAtom'
'THF.As.DefinedPlainTerm'
'THF.As.DefinedFunctor'
'THF.As.SystemTerm'
'THF.As.PrincipalSymbol'
'THF.As.Source'
'THF.As.DagSource'
'THF.As.ParentInfo'
'THF.As.IntroType'
'THF.As.ExternalSource'
'THF.As.FileSource'
'THF.As.TheoryName'
'THF.As.InfoItem'
'THF.As.FormulaItem'
'THF.As.InferenceItem'
'THF.As.InferenceStatus'
'THF.As.StatusValue'
'THF.As.GeneralTerm'
'THF.As.GeneralData'
'THF.As.GeneralFunction'
'THF.As.FormulaData'
'THF.As.Name'
'THF.As.AtomicWord'
'THF.As.Number'
'THF.Cons.THFBS'
'THF.Cons.BasicSpecTHF'
'THF.Cons.SentenceTHF'
'THF.Cons.SymbolTHF'
'THF.Cons.SymbolType'
'THF.Cons.Type'
'THF.Cons.Kind'
'THF.Sign.SignTHF'
'THF.Sign.TypeInfo'
'THF.Sign.ConstInfo'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
THF/As.hs
THF/Cons.hs
THF/Sign.hs
-}

module THF.ATC_THF () where

import ATC.GlobalAnnotations
import ATC.Id
import ATerm.Lib
import Common.DefaultMorphism
import Common.Id
import Common.Id hiding (typeId)
import Common.Result
import Data.Typeable
import THF.As
import THF.Cons
import THF.ParseTHF
import THF.ParseTHF0
import THF.Sign
import Text.ParserCombinators.Parsec
import qualified Data.Map as Map

{-! for THF.As.TPTP_THF derive : Typeable !-}
{-! for THF.As.Comment derive : Typeable !-}
{-! for THF.As.DefinedComment derive : Typeable !-}
{-! for THF.As.SystemComment derive : Typeable !-}
{-! for THF.As.Include derive : Typeable !-}
{-! for THF.As.Annotations derive : Typeable !-}
{-! for THF.As.FormulaRole derive : Typeable !-}
{-! for THF.As.THFFormula derive : Typeable !-}
{-! for THF.As.THFLogicFormula derive : Typeable !-}
{-! for THF.As.THFBinaryFormula derive : Typeable !-}
{-! for THF.As.THFBinaryTuple derive : Typeable !-}
{-! for THF.As.THFUnitaryFormula derive : Typeable !-}
{-! for THF.As.THFQuantifiedFormula derive : Typeable !-}
{-! for THF.As.THFVariable derive : Typeable !-}
{-! for THF.As.THFTypedConst derive : Typeable !-}
{-! for THF.As.THFTypeFormula derive : Typeable !-}
{-! for THF.As.THFTypeableFormula derive : Typeable !-}
{-! for THF.As.THFSubType derive : Typeable !-}
{-! for THF.As.THFTopLevelType derive : Typeable !-}
{-! for THF.As.THFUnitaryType derive : Typeable !-}
{-! for THF.As.THFBinaryType derive : Typeable !-}
{-! for THF.As.THFAtom derive : Typeable !-}
{-! for THF.As.THFDefinedVar derive : Typeable !-}
{-! for THF.As.THFSequent derive : Typeable !-}
{-! for THF.As.THFConnTerm derive : Typeable !-}
{-! for THF.As.THFQuantifier derive : Typeable !-}
{-! for THF.As.Quantifier derive : Typeable !-}
{-! for THF.As.THFPairConnective derive : Typeable !-}
{-! for THF.As.THFUnaryConnective derive : Typeable !-}
{-! for THF.As.AssocConnective derive : Typeable !-}
{-! for THF.As.DefinedType derive : Typeable !-}
{-! for THF.As.DefinedPlainFormula derive : Typeable !-}
{-! for THF.As.DefinedProp derive : Typeable !-}
{-! for THF.As.DefinedPred derive : Typeable !-}
{-! for THF.As.Term derive : Typeable !-}
{-! for THF.As.FunctionTerm derive : Typeable !-}
{-! for THF.As.PlainTerm derive : Typeable !-}
{-! for THF.As.DefinedTerm derive : Typeable !-}
{-! for THF.As.DefinedAtom derive : Typeable !-}
{-! for THF.As.DefinedPlainTerm derive : Typeable !-}
{-! for THF.As.DefinedFunctor derive : Typeable !-}
{-! for THF.As.SystemTerm derive : Typeable !-}
{-! for THF.As.PrincipalSymbol derive : Typeable !-}
{-! for THF.As.Source derive : Typeable !-}
{-! for THF.As.DagSource derive : Typeable !-}
{-! for THF.As.ParentInfo derive : Typeable !-}
{-! for THF.As.IntroType derive : Typeable !-}
{-! for THF.As.ExternalSource derive : Typeable !-}
{-! for THF.As.FileSource derive : Typeable !-}
{-! for THF.As.TheoryName derive : Typeable !-}
{-! for THF.As.InfoItem derive : Typeable !-}
{-! for THF.As.FormulaItem derive : Typeable !-}
{-! for THF.As.InferenceItem derive : Typeable !-}
{-! for THF.As.InferenceStatus derive : Typeable !-}
{-! for THF.As.StatusValue derive : Typeable !-}
{-! for THF.As.GeneralTerm derive : Typeable !-}
{-! for THF.As.GeneralData derive : Typeable !-}
{-! for THF.As.GeneralFunction derive : Typeable !-}
{-! for THF.As.FormulaData derive : Typeable !-}
{-! for THF.As.Name derive : Typeable !-}
{-! for THF.As.AtomicWord derive : Typeable !-}
{-! for THF.As.Number derive : Typeable !-}
{-! for THF.Cons.THFBS derive : Typeable !-}
{-! for THF.Cons.BasicSpecTHF derive : Typeable !-}
{-! for THF.Cons.SentenceTHF derive : Typeable !-}
{-! for THF.Cons.SymbolTHF derive : Typeable !-}
{-! for THF.Cons.SymbolType derive : Typeable !-}
{-! for THF.Cons.Type derive : Typeable !-}
{-! for THF.Cons.Kind derive : Typeable !-}
{-! for THF.Sign.SignTHF derive : Typeable !-}
{-! for THF.Sign.TypeInfo derive : Typeable !-}
{-! for THF.Sign.ConstInfo derive : Typeable !-}

{-! for THF.As.TPTP_THF derive : ShATermConvertible !-}
{-! for THF.As.Comment derive : ShATermConvertible !-}
{-! for THF.As.DefinedComment derive : ShATermConvertible !-}
{-! for THF.As.SystemComment derive : ShATermConvertible !-}
{-! for THF.As.Include derive : ShATermConvertible !-}
{-! for THF.As.Annotations derive : ShATermConvertible !-}
{-! for THF.As.FormulaRole derive : ShATermConvertible !-}
{-! for THF.As.THFFormula derive : ShATermConvertible !-}
{-! for THF.As.THFLogicFormula derive : ShATermConvertible !-}
{-! for THF.As.THFBinaryFormula derive : ShATermConvertible !-}
{-! for THF.As.THFBinaryTuple derive : ShATermConvertible !-}
{-! for THF.As.THFUnitaryFormula derive : ShATermConvertible !-}
{-! for THF.As.THFQuantifiedFormula derive : ShATermConvertible !-}
{-! for THF.As.THFVariable derive : ShATermConvertible !-}
{-! for THF.As.THFTypedConst derive : ShATermConvertible !-}
{-! for THF.As.THFTypeFormula derive : ShATermConvertible !-}
{-! for THF.As.THFTypeableFormula derive : ShATermConvertible !-}
{-! for THF.As.THFSubType derive : ShATermConvertible !-}
{-! for THF.As.THFTopLevelType derive : ShATermConvertible !-}
{-! for THF.As.THFUnitaryType derive : ShATermConvertible !-}
{-! for THF.As.THFBinaryType derive : ShATermConvertible !-}
{-! for THF.As.THFAtom derive : ShATermConvertible !-}
{-! for THF.As.THFDefinedVar derive : ShATermConvertible !-}
{-! for THF.As.THFSequent derive : ShATermConvertible !-}
{-! for THF.As.THFConnTerm derive : ShATermConvertible !-}
{-! for THF.As.THFQuantifier derive : ShATermConvertible !-}
{-! for THF.As.Quantifier derive : ShATermConvertible !-}
{-! for THF.As.THFPairConnective derive : ShATermConvertible !-}
{-! for THF.As.THFUnaryConnective derive : ShATermConvertible !-}
{-! for THF.As.AssocConnective derive : ShATermConvertible !-}
{-! for THF.As.DefinedType derive : ShATermConvertible !-}
{-! for THF.As.DefinedPlainFormula derive : ShATermConvertible !-}
{-! for THF.As.DefinedProp derive : ShATermConvertible !-}
{-! for THF.As.DefinedPred derive : ShATermConvertible !-}
{-! for THF.As.Term derive : ShATermConvertible !-}
{-! for THF.As.FunctionTerm derive : ShATermConvertible !-}
{-! for THF.As.PlainTerm derive : ShATermConvertible !-}
{-! for THF.As.DefinedTerm derive : ShATermConvertible !-}
{-! for THF.As.DefinedAtom derive : ShATermConvertible !-}
{-! for THF.As.DefinedPlainTerm derive : ShATermConvertible !-}
{-! for THF.As.DefinedFunctor derive : ShATermConvertible !-}
{-! for THF.As.SystemTerm derive : ShATermConvertible !-}
{-! for THF.As.PrincipalSymbol derive : ShATermConvertible !-}
{-! for THF.As.Source derive : ShATermConvertible !-}
{-! for THF.As.DagSource derive : ShATermConvertible !-}
{-! for THF.As.ParentInfo derive : ShATermConvertible !-}
{-! for THF.As.IntroType derive : ShATermConvertible !-}
{-! for THF.As.ExternalSource derive : ShATermConvertible !-}
{-! for THF.As.FileSource derive : ShATermConvertible !-}
{-! for THF.As.TheoryName derive : ShATermConvertible !-}
{-! for THF.As.InfoItem derive : ShATermConvertible !-}
{-! for THF.As.FormulaItem derive : ShATermConvertible !-}
{-! for THF.As.InferenceItem derive : ShATermConvertible !-}
{-! for THF.As.InferenceStatus derive : ShATermConvertible !-}
{-! for THF.As.StatusValue derive : ShATermConvertible !-}
{-! for THF.As.GeneralTerm derive : ShATermConvertible !-}
{-! for THF.As.GeneralData derive : ShATermConvertible !-}
{-! for THF.As.GeneralFunction derive : ShATermConvertible !-}
{-! for THF.As.FormulaData derive : ShATermConvertible !-}
{-! for THF.As.Name derive : ShATermConvertible !-}
{-! for THF.As.AtomicWord derive : ShATermConvertible !-}
{-! for THF.As.Number derive : ShATermConvertible !-}
{-! for THF.Cons.THFBS derive : ShATermConvertible !-}
{-! for THF.Cons.BasicSpecTHF derive : ShATermConvertible !-}
{-! for THF.Cons.SentenceTHF derive : ShATermConvertible !-}
{-! for THF.Cons.SymbolTHF derive : ShATermConvertible !-}
{-! for THF.Cons.SymbolType derive : ShATermConvertible !-}
{-! for THF.Cons.Type derive : ShATermConvertible !-}
{-! for THF.Cons.Kind derive : ShATermConvertible !-}
{-! for THF.Sign.SignTHF derive : ShATermConvertible !-}
{-! for THF.Sign.TypeInfo derive : ShATermConvertible !-}
{-! for THF.Sign.ConstInfo derive : ShATermConvertible !-}
