{-# OPTIONS -w -O0 #-}
{- |
Module      :  ATC/DevGraph.der.hs
Description :  generated Typeable, ShATermLG instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermLG
  for the type(s):
'Static.DevGraph.NodeSig'
'Static.DevGraph.MaybeNode'
'Static.DevGraph.Renamed'
'Static.DevGraph.MaybeRestricted'
'Static.DevGraph.DGOrigin'
'Static.DevGraph.DGNodeInfo'
'Static.DevGraph.DGNodeLab'
'Static.DevGraph.Fitted'
'Static.DevGraph.DGLinkOrigin'
'Static.DevGraph.DGLinkType'
'Static.DevGraph.DGLinkLab'
'Static.DevGraph.GenSig'
'Static.DevGraph.ExtGenSig'
'Static.DevGraph.ExtViewSig'
'Static.DevGraph.UnitSig'
'Static.DevGraph.ImpUnitSigOrSig'
'Static.DevGraph.RefSig'
'Static.DevGraph.BranchSig'
'Static.DevGraph.GlobalEntry'
'Static.DevGraph.DGChange'
'Static.DevGraph.HistElem'
'Static.DevGraph.RTNodeType'
'Static.DevGraph.RTNodeLab'
'Static.DevGraph.RTLinkType'
'Static.DevGraph.RTLinkLab'
'Static.DevGraph.DiagNodeLab'
'Static.DevGraph.DiagLinkLab'
'Static.DevGraph.Diag'
'Static.DevGraph.DGraph'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
Static/DevGraph.hs
-}

module ATC.DevGraph () where

import ATC.AS_Library
import ATC.Grothendieck
import ATC.XGraph
import ATerm.Lib
import Common.AS_Annotation
import Common.Consistency
import Common.GlobalAnnotations
import Common.IRI
import Common.Id
import Common.LibName
import Common.Result
import Control.Concurrent.MVar
import Data.Graph.Inductive.Basic
import Data.Graph.Inductive.Graph as Graph
import Data.Graph.Inductive.Query.DFS
import Data.List
import Data.Maybe
import Data.Ord
import Data.Typeable
import Logic.Comorphism
import Logic.ExtSign
import Logic.Grothendieck
import Logic.Logic
import Logic.Prover
import Static.DevGraph
import Static.DgUtils
import Static.GTheory
import Syntax.AS_Library
import Syntax.AS_Structured
import qualified Common.Lib.Graph as Tree
import qualified Common.Lib.MapSet as MapSet
import qualified Common.Lib.Rel as Rel
import qualified Common.Lib.SizedList as SizedList
import qualified Common.OrderedMap as OMap
import qualified Data.Map as Map
import qualified Data.Set as Set
import qualified Static.XGraph as XGraph

{-! for Static.DevGraph.NodeSig derive : Typeable !-}
{-! for Static.DevGraph.MaybeNode derive : Typeable !-}
{-! for Static.DevGraph.Renamed derive : Typeable !-}
{-! for Static.DevGraph.MaybeRestricted derive : Typeable !-}
{-! for Static.DevGraph.DGOrigin derive : Typeable !-}
{-! for Static.DevGraph.DGNodeInfo derive : Typeable !-}
{-! for Static.DevGraph.DGNodeLab derive : Typeable !-}
{-! for Static.DevGraph.Fitted derive : Typeable !-}
{-! for Static.DevGraph.DGLinkOrigin derive : Typeable !-}
{-! for Static.DevGraph.DGLinkType derive : Typeable !-}
{-! for Static.DevGraph.DGLinkLab derive : Typeable !-}
{-! for Static.DevGraph.GenSig derive : Typeable !-}
{-! for Static.DevGraph.ExtGenSig derive : Typeable !-}
{-! for Static.DevGraph.ExtViewSig derive : Typeable !-}
{-! for Static.DevGraph.UnitSig derive : Typeable !-}
{-! for Static.DevGraph.ImpUnitSigOrSig derive : Typeable !-}
{-! for Static.DevGraph.RefSig derive : Typeable !-}
{-! for Static.DevGraph.BranchSig derive : Typeable !-}
{-! for Static.DevGraph.GlobalEntry derive : Typeable !-}
{-! for Static.DevGraph.DGChange derive : Typeable !-}
{-! for Static.DevGraph.HistElem derive : Typeable !-}
{-! for Static.DevGraph.RTNodeType derive : Typeable !-}
{-! for Static.DevGraph.RTNodeLab derive : Typeable !-}
{-! for Static.DevGraph.RTLinkType derive : Typeable !-}
{-! for Static.DevGraph.RTLinkLab derive : Typeable !-}
{-! for Static.DevGraph.DiagNodeLab derive : Typeable !-}
{-! for Static.DevGraph.DiagLinkLab derive : Typeable !-}
{-! for Static.DevGraph.Diag derive : Typeable !-}
{-! for Static.DevGraph.DGraph derive : Typeable !-}

{-! for Static.DevGraph.NodeSig derive : ShATermLG !-}
{-! for Static.DevGraph.MaybeNode derive : ShATermLG !-}
{-! for Static.DevGraph.Renamed derive : ShATermLG !-}
{-! for Static.DevGraph.MaybeRestricted derive : ShATermLG !-}
{-! for Static.DevGraph.DGOrigin derive : ShATermLG !-}
{-! for Static.DevGraph.DGNodeInfo derive : ShATermLG !-}
{-! for Static.DevGraph.DGNodeLab derive : ShATermLG !-}
{-! for Static.DevGraph.Fitted derive : ShATermLG !-}
{-! for Static.DevGraph.DGLinkOrigin derive : ShATermLG !-}
{-! for Static.DevGraph.DGLinkType derive : ShATermLG !-}
{-! for Static.DevGraph.DGLinkLab derive : ShATermLG !-}
{-! for Static.DevGraph.GenSig derive : ShATermLG !-}
{-! for Static.DevGraph.ExtGenSig derive : ShATermLG !-}
{-! for Static.DevGraph.ExtViewSig derive : ShATermLG !-}
{-! for Static.DevGraph.UnitSig derive : ShATermLG !-}
{-! for Static.DevGraph.ImpUnitSigOrSig derive : ShATermLG !-}
{-! for Static.DevGraph.RefSig derive : ShATermLG !-}
{-! for Static.DevGraph.BranchSig derive : ShATermLG !-}
{-! for Static.DevGraph.GlobalEntry derive : ShATermLG !-}
{-! for Static.DevGraph.DGChange derive : ShATermLG !-}
{-! for Static.DevGraph.HistElem derive : ShATermLG !-}
{-! for Static.DevGraph.RTNodeType derive : ShATermLG !-}
{-! for Static.DevGraph.RTNodeLab derive : ShATermLG !-}
{-! for Static.DevGraph.RTLinkType derive : ShATermLG !-}
{-! for Static.DevGraph.RTLinkLab derive : ShATermLG !-}
{-! for Static.DevGraph.DiagNodeLab derive : ShATermLG !-}
{-! for Static.DevGraph.DiagLinkLab derive : ShATermLG !-}
{-! for Static.DevGraph.Diag derive : ShATermLG !-}
{-! for Static.DevGraph.DGraph derive : ShATermLG !-}
