{-# OPTIONS -w -O0 #-}
{- |
Module      :  ATC/OrderedMap.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'Common.OrderedMap.ElemWOrd'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
Common/OrderedMap.hs
-}

module ATC.OrderedMap () where

import ATerm.Lib
import Common.OrderedMap
import Data.Ord
import Data.Typeable
import Prelude hiding (lookup, map, filter, null)
import qualified Data.List as List
import qualified Data.Map as Map

{-! for Common.OrderedMap.ElemWOrd derive : Typeable !-}

{-! for Common.OrderedMap.ElemWOrd derive : ShATermConvertible !-}
