{-# OPTIONS -w -O0 #-}
{- |
Module      :  OWL2/ATC_OWL2.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'OWL2.AS.IRIType'
'OWL2.AS.QName'
'OWL2.AS.EquivOrDisjoint'
'OWL2.AS.DomainOrRange'
'OWL2.AS.SameOrDifferent'
'OWL2.AS.Relation'
'OWL2.AS.Character'
'OWL2.AS.PositiveOrNegative'
'OWL2.AS.QuantifierType'
'OWL2.AS.DatatypeCat'
'OWL2.AS.CardinalityType'
'OWL2.AS.Cardinality'
'OWL2.AS.JunctionType'
'OWL2.AS.Entity'
'OWL2.AS.EntityType'
'OWL2.AS.TypedOrUntyped'
'OWL2.AS.Literal'
'OWL2.AS.NNInt'
'OWL2.AS.IntLit'
'OWL2.AS.DecLit'
'OWL2.AS.FloatLit'
'OWL2.AS.ObjectPropertyExpression'
'OWL2.AS.DataRange'
'OWL2.AS.ClassExpression'
'OWL2.AS.Annotation'
'OWL2.AS.AnnotationValue'
'OWL2.Symbols.ExtEntityType'
'OWL2.Symbols.SymbItems'
'OWL2.Symbols.SymbMapItems'
'OWL2.Symbols.RawSymb'
'OWL2.Sign.Sign'
'OWL2.Sign.SignAxiom'
'OWL2.Sign.RoleKind'
'OWL2.Sign.RoleType'
'OWL2.Sign.DesKind'
'OWL2.Sign.DomainOrRangeOrFunc'
'OWL2.MS.Extended'
'OWL2.MS.ListFrameBit'
'OWL2.MS.AnnoType'
'OWL2.MS.AnnFrameBit'
'OWL2.MS.Fact'
'OWL2.MS.FrameBit'
'OWL2.MS.Frame'
'OWL2.MS.Axiom'
'OWL2.MS.Ontology'
'OWL2.MS.OntologyDocument'
'OWL2.Morphism.OWLMorphism'
'OWL2.ProfilesAndSublogics.ProfSub'
'OWL2.Sublogic.NumberRestrictions'
'OWL2.Sublogic.OWLSub'
'OWL2.Profiles.Profiles'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
OWL2/AS.hs
OWL2/Symbols.hs
OWL2/Sign.hs
OWL2/MS.hs
OWL2/Morphism.hs
OWL2/ProfilesAndSublogics.hs
OWL2/Sublogic.hs
OWL2/Profiles.hs
-}

module OWL2.ATC_OWL2 () where

import ATC.Result
import ATerm.Lib
import Common.Doc
import Common.DocUtils
import Common.Id
import Common.Lib.MapSet (setToMap)
import Common.Lib.State (execState)
import Common.Result
import Common.Utils (composeMap)
import Control.Monad
import Data.Char (intToDigit)
import Data.List
import Data.Maybe
import Data.Typeable
import OWL2.AS
import OWL2.ColonKeywords
import OWL2.Function
import OWL2.Keywords
import OWL2.MS
import OWL2.ManchesterPrint ()
import OWL2.Morphism
import OWL2.Profiles
import OWL2.ProfilesAndSublogics
import OWL2.Sign
import OWL2.StaticAnalysis
import OWL2.Sublogic
import OWL2.Symbols
import qualified Data.Map as Map
import qualified Data.Set as Set

{-! for OWL2.AS.IRIType derive : Typeable !-}
{-! for OWL2.AS.QName derive : Typeable !-}
{-! for OWL2.AS.EquivOrDisjoint derive : Typeable !-}
{-! for OWL2.AS.DomainOrRange derive : Typeable !-}
{-! for OWL2.AS.SameOrDifferent derive : Typeable !-}
{-! for OWL2.AS.Relation derive : Typeable !-}
{-! for OWL2.AS.Character derive : Typeable !-}
{-! for OWL2.AS.PositiveOrNegative derive : Typeable !-}
{-! for OWL2.AS.QuantifierType derive : Typeable !-}
{-! for OWL2.AS.DatatypeCat derive : Typeable !-}
{-! for OWL2.AS.CardinalityType derive : Typeable !-}
{-! for OWL2.AS.Cardinality derive : Typeable !-}
{-! for OWL2.AS.JunctionType derive : Typeable !-}
{-! for OWL2.AS.Entity derive : Typeable !-}
{-! for OWL2.AS.EntityType derive : Typeable !-}
{-! for OWL2.AS.TypedOrUntyped derive : Typeable !-}
{-! for OWL2.AS.Literal derive : Typeable !-}
{-! for OWL2.AS.NNInt derive : Typeable !-}
{-! for OWL2.AS.IntLit derive : Typeable !-}
{-! for OWL2.AS.DecLit derive : Typeable !-}
{-! for OWL2.AS.FloatLit derive : Typeable !-}
{-! for OWL2.AS.ObjectPropertyExpression derive : Typeable !-}
{-! for OWL2.AS.DataRange derive : Typeable !-}
{-! for OWL2.AS.ClassExpression derive : Typeable !-}
{-! for OWL2.AS.Annotation derive : Typeable !-}
{-! for OWL2.AS.AnnotationValue derive : Typeable !-}
{-! for OWL2.Symbols.ExtEntityType derive : Typeable !-}
{-! for OWL2.Symbols.SymbItems derive : Typeable !-}
{-! for OWL2.Symbols.SymbMapItems derive : Typeable !-}
{-! for OWL2.Symbols.RawSymb derive : Typeable !-}
{-! for OWL2.Sign.Sign derive : Typeable !-}
{-! for OWL2.Sign.SignAxiom derive : Typeable !-}
{-! for OWL2.Sign.RoleKind derive : Typeable !-}
{-! for OWL2.Sign.RoleType derive : Typeable !-}
{-! for OWL2.Sign.DesKind derive : Typeable !-}
{-! for OWL2.Sign.DomainOrRangeOrFunc derive : Typeable !-}
{-! for OWL2.MS.Extended derive : Typeable !-}
{-! for OWL2.MS.ListFrameBit derive : Typeable !-}
{-! for OWL2.MS.AnnoType derive : Typeable !-}
{-! for OWL2.MS.AnnFrameBit derive : Typeable !-}
{-! for OWL2.MS.Fact derive : Typeable !-}
{-! for OWL2.MS.FrameBit derive : Typeable !-}
{-! for OWL2.MS.Frame derive : Typeable !-}
{-! for OWL2.MS.Axiom derive : Typeable !-}
{-! for OWL2.MS.Ontology derive : Typeable !-}
{-! for OWL2.MS.OntologyDocument derive : Typeable !-}
{-! for OWL2.Morphism.OWLMorphism derive : Typeable !-}
{-! for OWL2.ProfilesAndSublogics.ProfSub derive : Typeable !-}
{-! for OWL2.Sublogic.NumberRestrictions derive : Typeable !-}
{-! for OWL2.Sublogic.OWLSub derive : Typeable !-}
{-! for OWL2.Profiles.Profiles derive : Typeable !-}

{-! for OWL2.AS.IRIType derive : ShATermConvertible !-}
{-! for OWL2.AS.QName derive : ShATermConvertible !-}
{-! for OWL2.AS.EquivOrDisjoint derive : ShATermConvertible !-}
{-! for OWL2.AS.DomainOrRange derive : ShATermConvertible !-}
{-! for OWL2.AS.SameOrDifferent derive : ShATermConvertible !-}
{-! for OWL2.AS.Relation derive : ShATermConvertible !-}
{-! for OWL2.AS.Character derive : ShATermConvertible !-}
{-! for OWL2.AS.PositiveOrNegative derive : ShATermConvertible !-}
{-! for OWL2.AS.QuantifierType derive : ShATermConvertible !-}
{-! for OWL2.AS.DatatypeCat derive : ShATermConvertible !-}
{-! for OWL2.AS.CardinalityType derive : ShATermConvertible !-}
{-! for OWL2.AS.Cardinality derive : ShATermConvertible !-}
{-! for OWL2.AS.JunctionType derive : ShATermConvertible !-}
{-! for OWL2.AS.Entity derive : ShATermConvertible !-}
{-! for OWL2.AS.EntityType derive : ShATermConvertible !-}
{-! for OWL2.AS.TypedOrUntyped derive : ShATermConvertible !-}
{-! for OWL2.AS.Literal derive : ShATermConvertible !-}
{-! for OWL2.AS.NNInt derive : ShATermConvertible !-}
{-! for OWL2.AS.IntLit derive : ShATermConvertible !-}
{-! for OWL2.AS.DecLit derive : ShATermConvertible !-}
{-! for OWL2.AS.FloatLit derive : ShATermConvertible !-}
{-! for OWL2.AS.ObjectPropertyExpression derive : ShATermConvertible !-}
{-! for OWL2.AS.DataRange derive : ShATermConvertible !-}
{-! for OWL2.AS.ClassExpression derive : ShATermConvertible !-}
{-! for OWL2.AS.Annotation derive : ShATermConvertible !-}
{-! for OWL2.AS.AnnotationValue derive : ShATermConvertible !-}
{-! for OWL2.Symbols.ExtEntityType derive : ShATermConvertible !-}
{-! for OWL2.Symbols.SymbItems derive : ShATermConvertible !-}
{-! for OWL2.Symbols.SymbMapItems derive : ShATermConvertible !-}
{-! for OWL2.Symbols.RawSymb derive : ShATermConvertible !-}
{-! for OWL2.Sign.Sign derive : ShATermConvertible !-}
{-! for OWL2.Sign.SignAxiom derive : ShATermConvertible !-}
{-! for OWL2.Sign.RoleKind derive : ShATermConvertible !-}
{-! for OWL2.Sign.RoleType derive : ShATermConvertible !-}
{-! for OWL2.Sign.DesKind derive : ShATermConvertible !-}
{-! for OWL2.Sign.DomainOrRangeOrFunc derive : ShATermConvertible !-}
{-! for OWL2.MS.Extended derive : ShATermConvertible !-}
{-! for OWL2.MS.ListFrameBit derive : ShATermConvertible !-}
{-! for OWL2.MS.AnnoType derive : ShATermConvertible !-}
{-! for OWL2.MS.AnnFrameBit derive : ShATermConvertible !-}
{-! for OWL2.MS.Fact derive : ShATermConvertible !-}
{-! for OWL2.MS.FrameBit derive : ShATermConvertible !-}
{-! for OWL2.MS.Frame derive : ShATermConvertible !-}
{-! for OWL2.MS.Axiom derive : ShATermConvertible !-}
{-! for OWL2.MS.Ontology derive : ShATermConvertible !-}
{-! for OWL2.MS.OntologyDocument derive : ShATermConvertible !-}
{-! for OWL2.Morphism.OWLMorphism derive : ShATermConvertible !-}
{-! for OWL2.ProfilesAndSublogics.ProfSub derive : ShATermConvertible !-}
{-! for OWL2.Sublogic.NumberRestrictions derive : ShATermConvertible !-}
{-! for OWL2.Sublogic.OWLSub derive : ShATermConvertible !-}
{-! for OWL2.Profiles.Profiles derive : ShATermConvertible !-}
