{-# OPTIONS -w -O0 #-}
{- |
Module      :  RelationalScheme/ATC_RelationalScheme.der.hs
Description :  generated Typeable, ShATermConvertible instances
Copyright   :  (c) DFKI Bremen 2008
License     :  GPLv2 or higher, see LICENSE.txt

Maintainer  :  Christian.Maeder@dfki.de
Stability   :  provisional
Portability :  non-portable(overlapping Typeable instances)

Automatic derivation of instances via DrIFT-rule Typeable, ShATermConvertible
  for the type(s):
'RelationalScheme.AS.RSRelType'
'RelationalScheme.AS.RSQualId'
'RelationalScheme.AS.RSRel'
'RelationalScheme.AS.RSRelationships'
'RelationalScheme.AS.RSScheme'
'RelationalScheme.Sign.RSDatatype'
'RelationalScheme.Sign.RSSymbol'
'RelationalScheme.Sign.RSColumn'
'RelationalScheme.Sign.RSTable'
'RelationalScheme.Sign.RSTables'
'RelationalScheme.Sign.RSTMap'
'RelationalScheme.Sign.RSMorphism'
-}

{-
  Generated by 'genRules' (automatic rule generation for DrIFT). Don't touch!!
  dependency files:
RelationalScheme/AS.hs
RelationalScheme/Sign.hs
-}

module RelationalScheme.ATC_RelationalScheme () where

import ATC.GlobalAnnotations
import ATerm.Lib
import Common.AS_Annotation
import Common.Doc
import Common.DocUtils
import Common.Id
import Common.Result
import Common.Utils
import Data.Typeable
import RelationalScheme.AS
import RelationalScheme.Keywords
import RelationalScheme.Sign
import qualified Data.Map as Map
import qualified Data.Set as Set

{-! for RelationalScheme.AS.RSRelType derive : Typeable !-}
{-! for RelationalScheme.AS.RSQualId derive : Typeable !-}
{-! for RelationalScheme.AS.RSRel derive : Typeable !-}
{-! for RelationalScheme.AS.RSRelationships derive : Typeable !-}
{-! for RelationalScheme.AS.RSScheme derive : Typeable !-}
{-! for RelationalScheme.Sign.RSDatatype derive : Typeable !-}
{-! for RelationalScheme.Sign.RSSymbol derive : Typeable !-}
{-! for RelationalScheme.Sign.RSColumn derive : Typeable !-}
{-! for RelationalScheme.Sign.RSTable derive : Typeable !-}
{-! for RelationalScheme.Sign.RSTables derive : Typeable !-}
{-! for RelationalScheme.Sign.RSTMap derive : Typeable !-}
{-! for RelationalScheme.Sign.RSMorphism derive : Typeable !-}

{-! for RelationalScheme.AS.RSRelType derive : ShATermConvertible !-}
{-! for RelationalScheme.AS.RSQualId derive : ShATermConvertible !-}
{-! for RelationalScheme.AS.RSRel derive : ShATermConvertible !-}
{-! for RelationalScheme.AS.RSRelationships derive : ShATermConvertible !-}
{-! for RelationalScheme.AS.RSScheme derive : ShATermConvertible !-}
{-! for RelationalScheme.Sign.RSDatatype derive : ShATermConvertible !-}
{-! for RelationalScheme.Sign.RSSymbol derive : ShATermConvertible !-}
{-! for RelationalScheme.Sign.RSColumn derive : ShATermConvertible !-}
{-! for RelationalScheme.Sign.RSTable derive : ShATermConvertible !-}
{-! for RelationalScheme.Sign.RSTables derive : ShATermConvertible !-}
{-! for RelationalScheme.Sign.RSTMap derive : ShATermConvertible !-}
{-! for RelationalScheme.Sign.RSMorphism derive : ShATermConvertible !-}

-- Generated by DrIFT, look but don't touch!

instance ShATermConvertible RSScheme where
  toShATermAux att0 xv = case xv of
    RSScheme a b c -> do
      (att1, a') <- toShATerm' att0 a
      (att2, b') <- toShATerm' att1 b
      (att3, c') <- toShATerm' att2 c
      return $ addATerm (ShAAppl "RSScheme" [a', b', c'] []) att3
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSScheme" [a, b, c] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      case fromShATerm' b att1 of
      { (att2, b') ->
      case fromShATerm' c att2 of
      { (att3, c') ->
      (att3, RSScheme a' b' c') }}}
    u -> fromShATermError "RSScheme" u

instance ShATermConvertible RSRelationships where
  toShATermAux att0 xv = case xv of
    RSRelationships a b -> do
      (att1, a') <- toShATerm' att0 a
      (att2, b') <- toShATerm' att1 b
      return $ addATerm (ShAAppl "RSRelationships" [a', b'] []) att2
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSRelationships" [a, b] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      case fromShATerm' b att1 of
      { (att2, b') ->
      (att2, RSRelationships a' b') }}
    u -> fromShATermError "RSRelationships" u

instance ShATermConvertible RSRel where
  toShATermAux att0 xv = case xv of
    RSRel a b c d -> do
      (att1, a') <- toShATerm' att0 a
      (att2, b') <- toShATerm' att1 b
      (att3, c') <- toShATerm' att2 c
      (att4, d') <- toShATerm' att3 d
      return $ addATerm (ShAAppl "RSRel" [a', b', c', d'] []) att4
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSRel" [a, b, c, d] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      case fromShATerm' b att1 of
      { (att2, b') ->
      case fromShATerm' c att2 of
      { (att3, c') ->
      case fromShATerm' d att3 of
      { (att4, d') ->
      (att4, RSRel a' b' c' d') }}}}
    u -> fromShATermError "RSRel" u

instance ShATermConvertible RSQualId where
  toShATermAux att0 xv = case xv of
    RSQualId a b c -> do
      (att1, a') <- toShATerm' att0 a
      (att2, b') <- toShATerm' att1 b
      (att3, c') <- toShATerm' att2 c
      return $ addATerm (ShAAppl "RSQualId" [a', b', c'] []) att3
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSQualId" [a, b, c] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      case fromShATerm' b att1 of
      { (att2, b') ->
      case fromShATerm' c att2 of
      { (att3, c') ->
      (att3, RSQualId a' b' c') }}}
    u -> fromShATermError "RSQualId" u

instance ShATermConvertible RSRelType where
  toShATermAux att0 xv = case xv of
    RSone_to_one -> return $ addATerm (ShAAppl "RSone_to_one" [] []) att0
    RSone_to_many -> return $ addATerm (ShAAppl "RSone_to_many" [] []) att0
    RSmany_to_one -> return $ addATerm (ShAAppl "RSmany_to_one" [] []) att0
    RSmany_to_many -> return $ addATerm (ShAAppl "RSmany_to_many" [] []) att0
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSone_to_one" [] _ -> (att0, RSone_to_one)
    ShAAppl "RSone_to_many" [] _ -> (att0, RSone_to_many)
    ShAAppl "RSmany_to_one" [] _ -> (att0, RSmany_to_one)
    ShAAppl "RSmany_to_many" [] _ -> (att0, RSmany_to_many)
    u -> fromShATermError "RSRelType" u

_tcRSSchemeTc :: TyCon
_tcRSSchemeTc = mkTyCon "RelationalScheme.AS.RSScheme"
instance Typeable RSScheme where
    typeOf _ = mkTyConApp _tcRSSchemeTc []

_tcRSRelationshipsTc :: TyCon
_tcRSRelationshipsTc = mkTyCon "RelationalScheme.AS.RSRelationships"
instance Typeable RSRelationships where
    typeOf _ = mkTyConApp _tcRSRelationshipsTc []

_tcRSRelTc :: TyCon
_tcRSRelTc = mkTyCon "RelationalScheme.AS.RSRel"
instance Typeable RSRel where
    typeOf _ = mkTyConApp _tcRSRelTc []

_tcRSQualIdTc :: TyCon
_tcRSQualIdTc = mkTyCon "RelationalScheme.AS.RSQualId"
instance Typeable RSQualId where
    typeOf _ = mkTyConApp _tcRSQualIdTc []

_tcRSRelTypeTc :: TyCon
_tcRSRelTypeTc = mkTyCon "RelationalScheme.AS.RSRelType"
instance Typeable RSRelType where
    typeOf _ = mkTyConApp _tcRSRelTypeTc []

instance ShATermConvertible RSMorphism where
  toShATermAux att0 xv = case xv of
    RSMorphism a b c d -> do
      (att1, a') <- toShATerm' att0 a
      (att2, b') <- toShATerm' att1 b
      (att3, c') <- toShATerm' att2 c
      (att4, d') <- toShATerm' att3 d
      return $ addATerm (ShAAppl "RSMorphism" [a', b', c', d'] []) att4
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSMorphism" [a, b, c, d] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      case fromShATerm' b att1 of
      { (att2, b') ->
      case fromShATerm' c att2 of
      { (att3, c') ->
      case fromShATerm' d att3 of
      { (att4, d') ->
      (att4, RSMorphism a' b' c' d') }}}}
    u -> fromShATermError "RSMorphism" u

instance ShATermConvertible RSTMap where
  toShATermAux att0 xv = case xv of
    RSTMap a -> do
      (att1, a') <- toShATerm' att0 a
      return $ addATerm (ShAAppl "RSTMap" [a'] []) att1
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSTMap" [a] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      (att1, RSTMap a') }
    u -> fromShATermError "RSTMap" u

instance ShATermConvertible RSTables where
  toShATermAux att0 xv = case xv of
    RSTables a -> do
      (att1, a') <- toShATerm' att0 a
      return $ addATerm (ShAAppl "RSTables" [a'] []) att1
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSTables" [a] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      (att1, RSTables a') }
    u -> fromShATermError "RSTables" u

instance ShATermConvertible RSTable where
  toShATermAux att0 xv = case xv of
    RSTable a b c d -> do
      (att1, a') <- toShATerm' att0 a
      (att2, b') <- toShATerm' att1 b
      (att3, c') <- toShATerm' att2 c
      (att4, d') <- toShATerm' att3 d
      return $ addATerm (ShAAppl "RSTable" [a', b', c', d'] []) att4
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSTable" [a, b, c, d] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      case fromShATerm' b att1 of
      { (att2, b') ->
      case fromShATerm' c att2 of
      { (att3, c') ->
      case fromShATerm' d att3 of
      { (att4, d') ->
      (att4, RSTable a' b' c' d') }}}}
    u -> fromShATermError "RSTable" u

instance ShATermConvertible RSColumn where
  toShATermAux att0 xv = case xv of
    RSColumn a b c -> do
      (att1, a') <- toShATerm' att0 a
      (att2, b') <- toShATerm' att1 b
      (att3, c') <- toShATerm' att2 c
      return $ addATerm (ShAAppl "RSColumn" [a', b', c'] []) att3
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSColumn" [a, b, c] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      case fromShATerm' b att1 of
      { (att2, b') ->
      case fromShATerm' c att2 of
      { (att3, c') ->
      (att3, RSColumn a' b' c') }}}
    u -> fromShATermError "RSColumn" u

instance ShATermConvertible RSSymbol where
  toShATermAux att0 xv = case xv of
    STable a -> do
      (att1, a') <- toShATerm' att0 a
      return $ addATerm (ShAAppl "STable" [a'] []) att1
    SColumn a b c d -> do
      (att1, a') <- toShATerm' att0 a
      (att2, b') <- toShATerm' att1 b
      (att3, c') <- toShATerm' att2 c
      (att4, d') <- toShATerm' att3 d
      return $ addATerm (ShAAppl "SColumn" [a', b', c', d'] []) att4
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "STable" [a] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      (att1, STable a') }
    ShAAppl "SColumn" [a, b, c, d] _ ->
      case fromShATerm' a att0 of
      { (att1, a') ->
      case fromShATerm' b att1 of
      { (att2, b') ->
      case fromShATerm' c att2 of
      { (att3, c') ->
      case fromShATerm' d att3 of
      { (att4, d') ->
      (att4, SColumn a' b' c' d') }}}}
    u -> fromShATermError "RSSymbol" u

instance ShATermConvertible RSDatatype where
  toShATermAux att0 xv = case xv of
    RSboolean -> return $ addATerm (ShAAppl "RSboolean" [] []) att0
    RSbinary -> return $ addATerm (ShAAppl "RSbinary" [] []) att0
    RSdate -> return $ addATerm (ShAAppl "RSdate" [] []) att0
    RSdatetime -> return $ addATerm (ShAAppl "RSdatetime" [] []) att0
    RSdecimal -> return $ addATerm (ShAAppl "RSdecimal" [] []) att0
    RSfloat -> return $ addATerm (ShAAppl "RSfloat" [] []) att0
    RSinteger -> return $ addATerm (ShAAppl "RSinteger" [] []) att0
    RSstring -> return $ addATerm (ShAAppl "RSstring" [] []) att0
    RStext -> return $ addATerm (ShAAppl "RStext" [] []) att0
    RStime -> return $ addATerm (ShAAppl "RStime" [] []) att0
    RStimestamp -> return $ addATerm (ShAAppl "RStimestamp" [] []) att0
    RSdouble -> return $ addATerm (ShAAppl "RSdouble" [] []) att0
    RSnonPosInteger -> return $ addATerm (ShAAppl "RSnonPosInteger" [] []) att0
    RSnonNegInteger -> return $ addATerm (ShAAppl "RSnonNegInteger" [] []) att0
    RSlong -> return $ addATerm (ShAAppl "RSlong" [] []) att0
    RSPointer -> return $ addATerm (ShAAppl "RSPointer" [] []) att0
  fromShATermAux ix att0 = case getShATerm ix att0 of
    ShAAppl "RSboolean" [] _ -> (att0, RSboolean)
    ShAAppl "RSbinary" [] _ -> (att0, RSbinary)
    ShAAppl "RSdate" [] _ -> (att0, RSdate)
    ShAAppl "RSdatetime" [] _ -> (att0, RSdatetime)
    ShAAppl "RSdecimal" [] _ -> (att0, RSdecimal)
    ShAAppl "RSfloat" [] _ -> (att0, RSfloat)
    ShAAppl "RSinteger" [] _ -> (att0, RSinteger)
    ShAAppl "RSstring" [] _ -> (att0, RSstring)
    ShAAppl "RStext" [] _ -> (att0, RStext)
    ShAAppl "RStime" [] _ -> (att0, RStime)
    ShAAppl "RStimestamp" [] _ -> (att0, RStimestamp)
    ShAAppl "RSdouble" [] _ -> (att0, RSdouble)
    ShAAppl "RSnonPosInteger" [] _ -> (att0, RSnonPosInteger)
    ShAAppl "RSnonNegInteger" [] _ -> (att0, RSnonNegInteger)
    ShAAppl "RSlong" [] _ -> (att0, RSlong)
    ShAAppl "RSPointer" [] _ -> (att0, RSPointer)
    u -> fromShATermError "RSDatatype" u

_tcRSMorphismTc :: TyCon
_tcRSMorphismTc = mkTyCon "RelationalScheme.Sign.RSMorphism"
instance Typeable RSMorphism where
    typeOf _ = mkTyConApp _tcRSMorphismTc []

_tcRSTMapTc :: TyCon
_tcRSTMapTc = mkTyCon "RelationalScheme.Sign.RSTMap"
instance Typeable RSTMap where
    typeOf _ = mkTyConApp _tcRSTMapTc []

_tcRSTablesTc :: TyCon
_tcRSTablesTc = mkTyCon "RelationalScheme.Sign.RSTables"
instance Typeable RSTables where
    typeOf _ = mkTyConApp _tcRSTablesTc []

_tcRSTableTc :: TyCon
_tcRSTableTc = mkTyCon "RelationalScheme.Sign.RSTable"
instance Typeable RSTable where
    typeOf _ = mkTyConApp _tcRSTableTc []

_tcRSColumnTc :: TyCon
_tcRSColumnTc = mkTyCon "RelationalScheme.Sign.RSColumn"
instance Typeable RSColumn where
    typeOf _ = mkTyConApp _tcRSColumnTc []

_tcRSSymbolTc :: TyCon
_tcRSSymbolTc = mkTyCon "RelationalScheme.Sign.RSSymbol"
instance Typeable RSSymbol where
    typeOf _ = mkTyConApp _tcRSSymbolTc []

_tcRSDatatypeTc :: TyCon
_tcRSDatatypeTc = mkTyCon "RelationalScheme.Sign.RSDatatype"
instance Typeable RSDatatype where
    typeOf _ = mkTyConApp _tcRSDatatypeTc []
